#-------------------------------
#config_example.yaml

#This is an example CAM diagnostics configuration file,
#which includes examples of each type of allowed input,
#along with a short description of what the input does.

#Currently this file can be used directly to test the
#diagnostics on either the NCAR Cheyenne or Casper machines.
#Other systems will require slight modifications, which are
#labeled in the comments below.

#Good luck!
#--------------------------------

#This first set of variables specify basic info required by all diagnostic runs:
diag_basic_info:

  #Is this a model vs observations comparison?
  #If "false", then a model-model comparison is assumed:
  compare_obs: true

  #Location of observational climatologies (only matters if "compare_obs" is true):
  #NOTE: How the observational data sets will be managed long-term needs to be discussed at some point!
  obs_climo_loc: /glade/work/brianpm/observations/climo_files

  #Name of CAM case (or CAM run name):
  cam_case_name: f2000.v211.fv1d.trop.L42.1

  #Location of CAM climatologies:
  cam_climo_loc: /glade/scratch/nusbaume/cam_diag_climo_files/f2000.v211.fv1d.trop.L42.1

  #Name of CAM baseline case (only matters if "compare_obs" is false):
  cam_baseline_case_name: best.cam_run-ever

  #Location of baseline CAM cliimatologies (only matters if "compare_obs" is false):
  cam_baseline_climo_loc: /some/where/you/want/to/have/it

  #Location where re-gridded CAM climatology files are stored:
  cam_regrid_loc: /glade/scratch/nusbaume/cam_diag_regrid_files/f2000.v211.fv1d.trop.L42.1

  #Overwrite CAM re-gridded files?
  #If false, then regridding will be skipped for regridded variables
  #that already exist in "cam_regrid_loc":
  cam_overwrite_regrid: true

  #Location where CAM diagnostic plots are stored:
  cam_diag_plot_loc: /glade/scratch/nusbaume/cam_diag_plots


#This second set of variables specify whether CAM climatologies need to be calculated:
diag_cam_climo:

  #Calculate cam climatologies?
  #If false, neither the climatology or time-series files will be created:
  calc_cam_climo: true

  #Overwrite CAM climatology files?
  #If false, then already existing climatology files will be skipped:
  cam_overwrite_climo: true

  #Location of CAM history (h0) files:
  cam_hist_loc: /glade/scratch/jcaron/archive/f2000.v211.fv1d.trop.L42.1/atm/hist

  #model year when climatology should start:
  start_year: 2000

  #model year when diagnostics should end:
  end_year: 2010

  #Save interim time series files?
  #WARNING:  This can take up a significant amount of space:
  cam_ts_save: true

  #Overwrite time series files, if found?
  #If set to false, then time series creation will be skipped if files are found:
  cam_overwrite_ts: false

  #Location where time series files are (or will be) stored:
  cam_ts_loc: /glade/scratch/nusbaume/cam_diag_ts_files/f2000.v211.fv1d.trop.L42.1


#This third set of variables specify whether CAM baseline climatologies need to be calculated
#This only matters if "compare_obs" is false:
diag_cam_baseline_climo:

  #Calculate cam baseline climatologies?
  #If false, neither the climatology or time-series files will be created:
  calc_cam_climo: false

  #Overwrite CAM climatology files?
  #If false, then already existing climatology files will be skipped:
  cam_overwrite_climo: false

  #Location of CAM history (h0) files:
  cam_hist_loc: /where/ever/you/want

  #model year when climatology should start:
  start_year: 1850

  #model year when diagnostics should end:
  end_year: 2100

  #Save interim time series files for baseline run?
  #WARNING:  This can take up a significant amount of space:
  cam_ts_save: false

  #Overwrite baseline time series files, if found?
  #If set to false, then time series creation will be skipped if files are found:
  cam_overwrite_ts: false

  #Location where time series files are (or will be) stored:
  cam_ts_loc: /another/location/on/computer

#+++++++++++++++++++++++++++++++++++++++++++++++++++
#These variables below only matter if you are using
#a non-standard method, or are adding your own
#diagnostic scripts.
#+++++++++++++++++++++++++++++++++++++++++++++++++++

#Name of time-averaging scripts being used to generate climatologies.
#These scripts must be located in "scripts/averaging":
time_averaging_scripts:
 - averaging_example

#Name of regridding scripts being used.
#These scripts must be located in "scripts/regridding":
regridding_scripts:
 - regrid_example

#List of plotting scripts being used.
#These scripts must be located in "scripts/plotting":
plotting_scripts:
 - plot_example

#List of CAM variables that will be processesd:
diag_var_list:
 - SWCF
 - LWCF

#List of observation types (filename prefixes) CAM can be compared against:
obs_type_list:
 - CERES_EBAF_Ed4.1

#END OF FILE
