#==============================
#config_cam_baseline.yaml

#This is the main CAM diagnostics config file
#for doing comparisons of a CAM run against
#another CAM run, or a CAM baseline simulation.

#Currently, if one is on NCAR's Casper
#machine, then only the CAM model data
#paths, case names, and model year spans
#are needed.  Running this diagnostics on
#a different machine, or with a different model,
#may require additional modifications.
#
#Config file Keywords:
#--------------------
#
#1.  Using ${xxx} will substitute that text with the
#    variable referenced by xxx. For example:
#
#    cam_case_name: cool_run
#    cam_climo_loc: /some/where/${cam_case_name}
#
#    will set "cam_climo_loc" in the diagnostics package to:
#    /some/where/cool_run
#
#2.  Using ${<top_level_section>.xxx} will do the same as
#    keyword 1 above, but specifies which sub-section the
#    variable is coming from, which is necessary for variables
#    that are repeated in different subsections.  For example:
#
#    diag_basic_info:
#      cam_climo_loc:  /some/where/${diag_cam_climo.start_year}
#
#    diag_cam_climo:
#      start_year: 1850
#
#    will set "cam_climo_loc" in the diagnostics package to:
#    /some/where/1850
#
#Please note that for both 1 and 2 the keywords must be lowercase.
#This is because future developments will hopefully use other keywords
#that are uppercase. Also please avoid using periods (".") in variable
#names, as this will likely cause issues with the current file parsing
#system.
#--------------------
#
##==============================

#This first set of variables specify basic info required by all diagnostic runs:
diag_basic_info:

  #Is this a model vs observations comparison?
  #If "false", then a model-model comparison is assumed:
  compare_obs: false

  #Generate HTML website:
  #Note:  The website files themselves will be located in the path
  #specified by "cam_diag_plot_loc", under the "<diag_run>/website" subdirectory,
  #where "<diag_run>" is the subdirectory created for this particular diagnostics run
  #(usually "case_vs_obs_XXX" or "case_vs_baseline_XXX").
  create_html: true

  #Location of observational climatologies (only matters if "compare_obs" is true):
  obs_climo_loc: /glade/work/brianpm/observations/climo_files

  #Name of CAM case (or CAM run name):
  cam_case_name: new_best.came-run

  #Location of CAM climatologies:
  cam_climo_loc: /some/where/you/want/to/have/it

  #Name of CAM baseline case (only matters if "compare_obs" is false):
  cam_baseline_case_name: best.cam_run-ever

  #Location of baseline CAM cliimatologies (only matters if "compare_obs" is false):
  cam_baseline_climo_loc: /some/where/else/you/want/to/have/it

  #Location where re-gridded CAM climatology files are stored:
  cam_regrid_loc: /any/directory/you/want

  #Overwrite CAM re-gridded files?
  #If false, then regridding will be skipped for regridded variables
  #that already exist in "cam_regrid_loc":
  cam_overwrite_regrid: false

  #Location where CAM diagnostic plots are stored:
  cam_diag_plot_loc: /any/other/directory/you/want


#This second set of variables specify whether CAM climatologies need to be calculated:
diag_cam_climo:

  #Calculate cam climatologies?
  #If false, neither the climatology or time-series files will be created:
  calc_cam_climo: true

  #Overwrite CAM climatology files?
  #If false, then already existing climatology files will be skipped:
  cam_overwrite_climo: false

  #Location of CAM history (h0) files:
  cam_hist_loc: /location/where/you/stored/model/outputs

  #model year when time series files should start:
  #Note:  Leaving this entry blank will make time series
  #       start at earliest available year.
  start_year: 1850

  #model year when time series files should end:
  #Note:  Leaving this entry blank will make time series
  #       end at latest available year.
  end_year: 2100

  #Do time series files need to be generated?
  #If True, then diagnostics assumes that model files are already time series.
  #If False, or if simply not present, then diagnostics will attempt to create
  #time series files from history (time-slice) files:
  cam_ts_done: false

  #Save interim time series files?
  #WARNING:  This can take up a significant amount of space:
  cam_ts_save: true

  #Overwrite time series files, if found?
  #If set to false, then time series creation will be skipped if files are found:
  cam_overwrite_ts: false

  #Location where time series files are (or will be) stored:
  cam_ts_loc: /some/big/storage/location/to/save/time/series


#This third set of variables specify whether CAM baseline climatologies need to be calculated
#This only matters if "compare_obs" is false:
diag_cam_baseline_climo:

  #Calculate cam baseline climatologies?
  #If false, neither the climatology or time-series files will be created:
  calc_cam_climo: true

  #Overwrite CAM climatology files?
  #If false, then already existing climatology files will be skipped:
  cam_overwrite_climo: false

  #Location of CAM history (h0) files:
  cam_hist_loc: /location/of/second/cam/run/output/or/baseline/data

  #model year when time series files should start:
  #Note:  Leaving this entry blank will make diagnostics
  #       start at earliest available year.
  start_year: 1850

  #model year when time series files should end:
  #Note:  Leaving this entry blank will make diagnostics
  #       end at latest available year.
  end_year: 2100

  #Do time series files need to be generated?
  #If True, then diagnostics assumes that model files are already time series.
  #If False, or if simply not present, then diagnostics will attempt to create
  #time series files from history (time-slice) files:
  cam_ts_done: false

  #Save interim time series files for baseline run?
  #WARNING:  This can take up a significant amount of space:
  cam_ts_save: true

  #Overwrite baseline time series files, if found?
  #If set to false, then time series creation will be skipped if files are found:
  cam_overwrite_ts: false

  #Location where time series files are (or will be) stored:
  cam_ts_loc: /another/big/storage/location/to/save/time/series

#+++++++++++++++++++++++++++++++++++++++++++++++++++
#These variables below only matter if you are using
#a non-standard method, or are adding your own
#diagnostic scripts.
#+++++++++++++++++++++++++++++++++++++++++++++++++++

#Note:  If you want to pass arguments to a particular script, you can
#do it like so (using the "averaging_example" script in this case):
# - {averaging_example: {kwargs: {clobber: true}}}

#Name of time-averaging scripts being used to generate climatologies.
#These scripts must be located in "scripts/averaging":
time_averaging_scripts:
 - averaging_example

#Name of regridding scripts being used.
#These scripts must be located in "scripts/regridding":
regridding_scripts:
 - regrid_example

#List of analysis scripts being used.
#These scripts must be located in "scripts/analysis":
analysis_scripts:
 - amwg_table

#List of plotting scripts being used.
#These scripts must be located in "scripts/plotting":
plotting_scripts:
 - global_latlon_map
 - zonal_mean

#List of CAM variables that will be processesd:
diag_var_list:
 - SWCF
 - LWCF
 - PSL
 - Q
#<Add more variables here.>

#List of observation types (filename prefixes) CAM can be compared against:
obs_type_list:
 - CERES_EBAF_Ed4.1

#END OF FILE
